version: '3.9'

services:
  teamspeak:
    build:
      context: ../..
      dockerfile: alpine/Dockerfile
      args:
        IMAGE_ALPINE_NAME: ${IMAGE_ALPINE_NAME}
        IMAGE_ALPINE_VERSION: ${IMAGE_ALPINE_3_19_VERSION}
        TEAMSPEAK_CHECKSUM: ${TEAMSPEAK_CHECKSUM}
        TEAMSPEAK_VERSION: ${TEAMSPEAK_VERSION}
        TIMEZONE: ${TIMEZONE}
      cache_from:
      - ${BUILD_IMAGE_NAME}:${BUILD_IMAGE_VERSION}-${BUILD_IMAGE_NUMBER}-alpine3.19-rc
      - ${BUILD_IMAGE_NAME}:${BUILD_IMAGE_VERSION}-${BUILD_IMAGE_NUMBER}-alpine3.19-dev
      - ${BUILD_IMAGE_NAME}:${BUILD_IMAGE_VERSION}-${BUILD_IMAGE_NUMBER}-alpine3.19-test
      - ${BUILD_IMAGE_NAME}:${BUILD_IMAGE_VERSION}-${BUILD_IMAGE_NUMBER}-alpine3.19
    image: ${BUILD_IMAGE_NAME}:${BUILD_IMAGE_VERSION}-${BUILD_IMAGE_NUMBER}-alpine3.19-rc
